CREATE DATABASE TEMP2;
USE TEMP2;
CREATE TABLE STUDENT(
id INT PRIMARY KEY,
name VARCHAR (50),
age INT NOT NULL
);
INSERT INTO STUDENT VALUES(1, "AJAY", 22);
INSERT INTO STUDENT VALUES(2, "HEMANT", 25);

SELECT * FROM STUDENT;
