CREATE DATABASE 5JAN;
USE 5JAN;

CREATE TABLE JJJ(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE VARCHAR(50)
);

INSERT INTO JJJ
(ID,NAME, AGE)
VALUES
(101, "AJAY", 21),
(102, "HEMANT", 25);

SELECT ID FROM JJJ;

CREATE TABLE DEF (
ID INT PRIMARY KEY,
SALARY INT DEFAULT 25000
);

INSERT INTO DEF VALUES(101,2000);
INSERT INTO DEF(ID) VALUES(102);

SELECT * FROM DEF;

CREATE TABLE DEF1(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
GRADE VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO DEF1
(ID, NAME, GRADE, CITY, AGE)
VALUES
(101, "AJAY", "A", "BPL", 21),
(102, "HEMANT", "B", "BASODA", 25),
(103, "POOJA", "A", "PUNE", 27),
(104, "ARTI", "B", "DEHLI", 30),
(105, "RAHUL", "C", "GUNJ", 29);

SELECT DISTINCT GRADE FROM DEF1;
SELECT * FROM DEF1 LIMIT 3;

SELECT * FROM DEF1 WHERE AGE>=21 OR CITY= "GUNJ";
SELECT * FROM DEF1 WHERE GRADE="A";

SELECT * FROM DEF1 WHERE AGE BETWEEN  25 AND 30;
SELECT * FROM DEF1 WHERE AGE>=21 OR CITY= "GUNJ";
SELECT * FROM DEF1 WHERE CITY IN  ("GUNJ", "PUNE)";

SELECT * FROM DEF1 
ORDER BY CITY ASC;

SELECT * FROM DEF1 
ORDER BY GRADE DESC;

SELECT MAX(CITY) FROM DEF1 ;
SELECT MIN(ID) FROM DEF1 ;
SELECT COUNT(CITY) FROM DEF1 ;
SELECT SUM(ID) FROM DEF1 ;
SELECT AVG(ID) FROM DEF1 ;

SELECT CITY, COUNT(CITY)
FROM DEF1
GROUP BY CITY;

SELECT NAME, MAX(NAME)
FROM DEF1
GROUP BY NAME;

SELECT CITY , COUNT(ID)
FROM DEF1 
GROUP BY CITY;

SELECT GRADE, COUNT(ID)
FROM DEF1
GROUP BY GRADE
HAVING MAX(AGE)>26;

SELECT CITY,COUNT(ID)
FROM DEF1
WHERE GRADE="A"
GROUP BY CITY
HAVING MAX(ID)>=101
ORDER BY CITY DESC;

SET SQL_SAFE_UPDATES=0;

UPDATE DEF1
SET GRADE="BB"
WHERE GRADE="B";

UPDATE DEF1
SET AGE=AGE+1;

UPDATE DEF1
SET AGE=AGE-1;

INSERT INTO DEF1 VALUES(106,"AAAA", "O", "BHOPAL",11 );

DELETE FROM DEF1
WHERE GRADE="O";

SELECT * FROM DEF1;

CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO DEPARTMENT
(ID,NAME)
VALUES
(101, "HINDI"),
(102, "ENGLISH"),
(103, "MATH");

CREATE TABLE TEACHER(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
COURSE_ID INT,
FOREIGN KEY (COURSE_ID) REFERENCES DEPARTMENT(ID)
);

INSERT INTO TEACHER
(ID,NAME, COURSE_ID)
VALUES
(101, "AJAY", 102),
(102,"ARTI",102),
(103, "POOJA", 103),
(104, "HEMANT", 101);

SELECT * FROM TEACHER;

/* CASCADING */

CREATE TABLE DEPARTMENT1(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO DEPARTMENT1
(ID,NAME)
VALUES
(101, "HINDI"),
(102, "ENGLISH"),
(103, "MATH");

INSERT INTO DEPARTMENT1 VALUES (201,"CLOUD_COMPUTING");

UPDATE DEPARTMENT1
SET ID=202
WHERE ID=102;

SELECT * FROM DEPARTMENT1;

CREATE TABLE TEACHER1(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
COURSE_ID INT,
FOREIGN KEY (COURSE_ID) REFERENCES DEPARTMENT1(ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO TEACHER1
(ID,NAME, COURSE_ID)
VALUES
(101, "AJAY", 102),
(102,"ARTI",102),
(103, "POOJA", 103),
(104, "HEMANT", 101);

DROP  TABLE TEACHER1;

SELECT * FROM TEACHER1;

ALTER TABLE DEF1
ADD COLUMN DOB INT;

ALTER TABLE DEF1
DROP COLUMN DOB;

ALTER TABLE DEF1
ADD COLUMN STATE VARCHAR(30) NOT NULL DEFAULT "VIDISHA";

ALTER TABLE  DEF1
MODIFY COLUMN AGE3 VARCHAR(2);

ALTER TABLE DEF1
CHANGE COLUMN AGE3 STUDENT_AGE INT;

INSERT INTO DEF1
(ID,NAME,STUDENT_AGE)
VALUES
(110,"AMAN", "100");

ALTER TABLE DEF111 
RENAME TO DEF1;

ALTER TABLE DEF1
CHANGE NAME FULL_NAME VARCHAR(50);

ALTER TABLE DEF1
CHANGE FULL_NAME NAME VARCHAR(50);

SET SQL_SAFE_UPDATES=0;

DELETE FROM DEF1
WHERE GRADE="C";

UPDATE DEF1
SET GRADE="B"
WHERE GRADE="BB";

/* JOINS IN SQL */
/* INNER JOIN */

CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT
(ID,NAME)
VALUES
(101,"AJAY"),
(102,"HEMANT"),
(104,"POOJA");

CREATE TABLE TEACH(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50)
);

INSERT INTO TEACH
(ID ,SUBJECT)
VALUES
(101,"ENGLISH"),
(102,"HINDI"),
(105,"MATH"),
(106,"JAY");

SELECT *
FROM STUDENT
INNER JOIN TEACH
ON STUDENT.ID=TEACH.ID;

SELECT * FROM TEACH;

/* LEFT JOIN */

CREATE TABLE STUDENT1(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT1
(ID, NAME)
VALUES
(101,"AJAY"),
(102,"JAY"),
(106,"AYAN");

CREATE TABLE TEACH1(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50)
);

INSERT INTO TEACH1
(ID,SUBJECT )
VALUES
(101,"HINDI"),
(103,"MATH"),
(107,"ENGLISH");

SELECT *
FROM STUDENT1
LEFT JOIN TEACH1
ON STUDENT1.ID=TEACH1.ID;

/* RIGHT JOIN */

CREATE TABLE STUDENT2(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT2
(ID, NAME)
VALUES
(101,"AJAY"),
(102,"JAY"),
(106,"AYAN");

CREATE TABLE TEACH2(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO TEACH2
(ID, NAME)
VALUES
(101,"CLOUD"),
(103,"DBMS"),
(106,"RDBMS"),
(107,"DSA");

SELECT * 
FROM STUDENT2
RIGHT JOIN TEACH2
ON STUDENT2.ID=TEACH2.ID;

/* FULL JOIN */

CREATE TABLE STUDENT3(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT3
(ID, NAME)
VALUES
(101,"AJAY"),
(102,"JAY"),
(106,"AYAN");

CREATE TABLE TEACH3(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50)
);

INSERT INTO TEACH3
(ID, SUBJECT)
VALUES
(101,"CLOUD"),
(103,"DBMS"),
(106,"RDBMS"),
(107,"DSA");


SELECT *
FROM STUDENT3
LEFT JOIN TEACH3
ON STUDENT3.ID=TEACH3.ID
UNION
SELECT *
FROM STUDENT3
RIGHT JOIN TEACH3
ON STUDENT3.ID=TEACH3.ID;

/* LEFT EXCLUSIVE JOIN */

CREATE TABLE STUDENT4(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT4
(ID, NAME)
VALUES
(101,"AJAY"),
(102,"JAY"),
(106,"AYAN");

CREATE TABLE TEACH4(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50)
);

INSERT INTO TEACH4
(ID, SUBJECT)
VALUES
(101,"CLOUD"),
(103,"DBMS"),
(106,"RDBMS"),
(107,"DSA");


SELECT *
FROM STUDENT4 AS S
LEFT JOIN TEACH4 AS T
ON S.ID=T.ID
WHERE T.ID IS NULL;

/* RIGHT EXCLUSIVE JOIN */

CREATE TABLE STUDENT5(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO STUDENT5
(ID, NAME)
VALUES
(101,"AJAY"),
(102,"JAY"),
(106,"AYAN");

CREATE TABLE TEACH5(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50)
);

INSERT INTO TEACH5
(ID, SUBJECT)
VALUES
(101,"CLOUD"),
(103,"DBMS"),
(106,"RDBMS"),
(107,"DSA");


SELECT *
FROM STUDENT5 AS S
RIGHT JOIN TEACH5 AS T
ON S.ID=T.ID
WHERE S.ID IS NULL;

/* SELF JOIN */

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(50), 
MANAGER_ID INT
);

INSERT INTO EMPLOYEE
(ID,NAME, MANAGER_ID)
VALUES
(101, "ADAM",103),
(102, "BOB",104),
(103, "CASSY", NULL),
(104, "DOLALT",103);

SELECT *
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID=B.MANAGER_ID;

SELECT A.NAME , B.NAME
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID=B.MANAGER_ID;

SELECT A.NAME AS MANAGER_NAME , B.NAME
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID=B.MANAGER_ID;

/* UNION */

SELECT NAME FROM EMPLOYEE
UNION
SELECT NAME FROM EMPLOYEE;

SELECT NAME FROM EMPLOYEE
UNION ALL
SELECT NAME FROM EMPLOYEE;

/* SUB QUERIRS */

CREATE TABLE UNIVERSITY(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT
);

INSERT INTO UNIVERSITY
(ID,NAME, MARKS)
VALUES
(101,"AJAY",95),
(102,"POOJA",90),
(103,"ARTI",80),
(104,"HEMANT",74),
(105,"RAHUL",70);

SELECT * FROM UNIVERSITY;

SELECT AVG(MARKS)
FROM UNIVERSITY;

SELECT NAME,MARKS
FROM UNIVERSITY
WHERE MARKS>81.8000;

SELECT NAME,MARKS
FROM UNIVERSITY
WHERE MARKS>(SELECT AVG(MARKS)
FROM UNIVERSITY
);

SELECT ID
FROM UNIVERSITY
WHERE ID%2=0;

SELECT ID,NAME
FROM UNIVERSITY
WHERE ID  IN(102,104);

SELECT *
FROM UNIVERSITY
WHERE ID  IN(SELECT ID
FROM UNIVERSITY
WHERE ID%2=0
);

SELECT *
FROM UNIVERSITY
WHERE ID=105;

CREATE VIEW VIEW1 AS
SELECT ID, NAME FROM UNIVERSITY;

DROP VIEW VIEW1 ;

SELECT * FROM VIEW1;

SELECT * 
FROM VIEW1
WHERE MARKS>89;